name: Actions

on:
  push:
    branches:
      - master

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Decrypt configuration file
        run: sh ./.github/scripts/decrypt_secret.sh
        env:
          SECRET_PASSPHRASE: ${{secrets.SECRET_PASSPHRASE}}

      - name: Install PHP dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist

      - name: Install Node.js dependencies
        run: npm install

      - name: Run the test suite
        run: ./vendor/bin/paratest

      - name: Archive snapshot
        run: zip -r snapshot.zip ./

      - name: Upload snapshot
        uses: actions/upload-artifact@master
        with:
          name: snapshot
          path: snapshot.zip
